
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Oct 15 14:26:09 BRT 2015
//----------------------------------------------------

package main;

/** CUP generated interface containing symbol constants. */
public interface ParserSym {
  /* terminals */
  public static final int A_FAT = 38;
  public static final int K_NEW = 23;
  public static final int COLCHE_ESQ = 12;
  public static final int PONTOVIRGULA = 4;
  public static final int K_LENGTH = 25;
  public static final int B_FALSE = 34;
  public static final int K_MAIN = 24;
  public static final int K_THIS = 22;
  public static final int OP_AND = 27;
  public static final int K_PRINT = 26;
  public static final int K_EXTENDS = 16;
  public static final int T_INT = 30;
  public static final int K_IF = 19;
  public static final int PARENT_ESQ = 8;
  public static final int VIRGULA = 6;
  public static final int PONTO = 5;
  public static final int IDENTIFICADOR = 3;
  public static final int IGUAL = 7;
  public static final int CURLY_ESQ = 10;
  public static final int COLCHE_DIR = 13;
  public static final int K_STATIC = 17;
  public static final int K_ELSE = 20;
  public static final int A_MINUS = 36;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int OP_LT = 28;
  public static final int B_TRUE = 33;
  public static final int K_CLASS = 14;
  public static final int A_MULT = 37;
  public static final int PARENT_DIR = 9;
  public static final int K_RETURN = 21;
  public static final int LITERAL_INTEIRO = 2;
  public static final int T_STRING = 32;
  public static final int T_BOOLEAN = 31;
  public static final int CURLY_DIR = 11;
  public static final int K_PUBLIC = 15;
  public static final int A_PLUS = 35;
  public static final int T_VOID = 29;
  public static final int K_WHILE = 18;
}

